version: "3.8"
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/dump:/dump

  app:
    build: .
    image: 172.16.2.239:8083/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mongo-data:
    driver: local
# version: "3"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mongo
#     environment:
#       MONGO_URI: mongodb://mongo:27017/metamatch

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:

# version: "3.8"
# services:
#   db:
#     image: mongo:4.2
#     container_name: db
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     ports:
#       - 27017:27017
#     volumes:
#       - ./data/dump:/dump

#   app:
#     build: .
#     image: 172.16.2.239:8083/nodemongoapp:6.0
#     restart: always
#     container_name: back
#     ports:
#       - "5000:5000"
#     environment:
#       MONGO_URI: mongodb://db:27017/metamatch
#     depends_on:
#       - db

# volumes:
#   mongo-data:

